-- SAFE FIX SCRIPT
-- Run this to fix the "already exists" errors.
-- It will safely remove old settings and apply the correct ones.

-- 1. Drop old policies if they exist (cleans up the error)
drop policy if exists "Users can view own profile" on profiles;
drop policy if exists "Users can update own profile" on profiles;
drop policy if exists "Users can view own records" on time_records;
drop policy if exists "Users can insert own records" on time_records;
drop policy if exists "Users can update own records" on time_records;

-- 2. Create the Tables (if they don't exist yet)
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  name text,
  email text
);

create table if not exists time_records (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  check_in timestamptz not null,
  check_out timestamptz
);

-- 3. Enable Security
alter table profiles enable row level security;
alter table time_records enable row level security;

-- 4. Re-create Policies (Now safe because we dropped them above)
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

create policy "Users can view own records" on time_records for select using (auth.uid() = user_id);
create policy "Users can insert own records" on time_records for insert with check (auth.uid() = user_id);
create policy "Users can update own records" on time_records for update using (auth.uid() = user_id);

-- 5. Set up the Auto-User Trigger
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, email)
  values (new.id, new.raw_user_meta_data->>'name', new.email);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
