-- Copy this SQL into your Supabase SQL Editor to set up the database

-- 1. Create a table for user profiles (extends default auth.users)
create table profiles (
  id uuid references auth.users not null primary key,
  name text,
  email text
);

-- 2. Create a table for time records
create table time_records (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  check_in timestamptz not null,
  check_out timestamptz
);

-- 3. Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table time_records enable row level security;

-- 4. Create Policies for Profiles
-- Users can see their own profile
create policy "Users can view own profile" 
  on profiles for select 
  using (auth.uid() = id);

-- Users can update their own profile
create policy "Users can update own profile" 
  on profiles for update 
  using (auth.uid() = id);

-- 5. Create Policies for Time Records
-- Users can see only their own records
create policy "Users can view own records" 
  on time_records for select 
  using (auth.uid() = user_id);

-- Users can only insert records for themselves
create policy "Users can insert own records" 
  on time_records for insert 
  with check (auth.uid() = user_id);

-- Users can update only their own records
create policy "Users can update own records" 
  on time_records for update 
  using (auth.uid() = user_id);

-- 6. Create a Trigger to automatically create a profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, email)
  values (new.id, new.raw_user_meta_data->>'name', new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
